project:
  type: website
  output-dir: docs
  
lang: en

execute:
  freeze: false
  cache: false
  
format:
  html:
    theme:
      light: minty
      dark: darkly
    callout-appearence: simple
    css: assets/styles.css
    toc: true
    toc-depth: 4
    smooth-scroll: true
    highlight-style: atom-one
    number-sections: true
    number-depth: 4
    pagetite: "{{< var meta.title>}}"

website:
  repo-url: https://github.com/UCLPG-MSC-SGDS/BISemWeb2025
  repo-actions: [issue]
  page-navigation: true
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 2
    logo: images/general/BISemWeb2025_logo.png
    tools:
      - icon: github
        href: https://github.com/UCLPG-MSC-SGDS/BISemWeb2025
    contents:
      - section: "Overview"
        contents: 
          text: "Welcome"
          file: 00-index.qmd
      - section: "Getting Started"
        contents:
          - 01-installation.qmd
          - 02-reading_list.qmd
      - section: "Practical Sessions"
        contents:



